name: safe-exceptions-checked
version: 0.1.0
synopsis: Safe, checked exceptions
description: >
  Machinery for throwing and catching both pure and impure synchronous
  exceptions. Based on <https://www.well-typed.com/blog/2015/07/checked-exceptions/ Lightweight Checked Exceptions>
  by Edsko de Vries and Adam Gundry.
category: Control
stability: Unknown
author:
  - Edsko de Vries
  - Adam Gundry
  - Mitchell Rosen
maintainer: Mitchell Rosen
copyright: 2017 Mitchell Rosen
license: BSD3
github: mitchellwrosen/safe-exceptions-checked
ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base            >= 4.7     && < 5
    - deepseq
    - safe-exceptions >= 0.1.1   && < 0.1.7
    - transformers    >= 0.2.0.0 && < 0.6

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - base
      - hspec
      - safe-exceptions-checked
